const IMPORT_ALL = 'IMPORT_ALL';
const VUE_MODULE = 'VUE_MODULE';
const UNNAMED_DEFAULT = 'UNNAMED_DEFAULT';
const UNNAMED_FUNCTION = 'UNNAMED_FUNCTION';
const DECONSTRUCTION_STATEMENT_SYMBOLS = new Set(['let', 'var', 'const']);

module.exports = {
    IMPORT_ALL,
    VUE_MODULE,
    UNNAMED_DEFAULT,
    UNNAMED_FUNCTION,
    DECONSTRUCTION_STATEMENT_SYMBOLS
}